/* eslint-disable @next/next/no-img-element */
import './globals.css'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'

import { libre, lato, montserrat } from '../styles/fonts'
import Image from 'next/image'
// <<<<<<< forSeoWork
// =======
export const metadata = {
  title: 'Chickadee Retreat',
  description: 'Generated by create next app'
}
// >>>>>>> main

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${libre.variable} ${lato.variable}`}>
        <header className='flex flex-col gap-10 items-center pt-8 pb-8 bg-green'>
          <figure>
            <Image
              className='h-full w-[7rem]'
              src='/icon.png'
              width={200}
              height={200}
              alt='logo'
            />
          </figure>
          <h1 className='text-[#C3BCAC]'>Chickadee Retreats</h1>
          <NavBar />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  )
}
